# Generated by Django 5.1.1 on 2024-10-09 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auctionlisting_watchlist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bid',
            old_name='listing',
            new_name='auction_listing',
        ),
        migrations.RenameField(
            model_name='bid',
            old_name='user',
            new_name='bidder',
        ),
    ]
